name: build-and-push

on:
  push:                  # ← ajoute ces deux lignes
    branches: [main]     #    (surveille la branche main)
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'  # 04:00 Paris, tous les jours

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - uses: docker/setup-buildx-action@v3

    - uses: docker/login-action@v3
      with:
        username: diablotin74
        password: ${{ secrets.DOCKERHUBCLI }}

    - name: Build & push Gemini
      uses: docker/build-push-action@v5
      with:
        context: ./gemini
        push: true
        tags: diablotin74/gemini-cli:latest

    - name: Build & push Claude
      uses: docker/build-push-action@v5
      with:
        context: ./claude
        push: true
        tags: diablotin74/claude-cli:latest

    - name: Build & push Codex
      uses: docker/build-push-action@v5
      with:
        context: ./codex
        push: true
        tags: diablotin74/codex-cli:latest
